name: Validate JSON
on:
  - push
  - pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate config.json
        uses: 'docker://cytopia/jsonlint'
        with:
          args: '-t "  " /github/workspace/config.json'
      - name: Validate versions.json
        uses: 'docker://cytopia/jsonlint'
        with:
          args: '-t "  " /github/workspace/versions.json'
